export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT';
export const REQUEST_SUBREDDITS = 'REQUEST_SUBREDDITS';
export const RECEIVE_SUBREDDITS = 'RECEIVE_SUBREDDITS';
export const NEED_REFRESH = 'NEED_REFRESH';
